#!/bin/bash
set -e

case "$1" in
    remove|purge)
        # Update desktop database
        if [ -x /usr/bin/update-desktop-database ]; then
            update-desktop-database /usr/share/applications
        fi

        # Update icon cache
        if [ -x /usr/bin/gtk-update-icon-cache ]; then
            gtk-update-icon-cache -f /usr/share/icons/hicolor
        fi
        ;;
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
